"""
PDF forensic report generator using ReportLab.
Generates a multi-page professional report from analysis results.
"""
import html
import io
import os
from typing import Any
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    PageBreak, HRFlowable, KeepTogether
)
from reportlab.pdfgen import canvas

# Colors
C_NAVY = colors.HexColor("#0F172A")
C_BLUE = colors.HexColor("#1E3A8A")
C_ACCENT = colors.HexColor("#2563EB")
C_TEXT = colors.HexColor("#1E293B")
C_MUTED = colors.HexColor("#64748B")
C_BORDER = colors.HexColor("#CBD5E1")
C_BG = colors.HexColor("#F8FAFC")
C_GREEN = colors.HexColor("#22C55E")
C_RED = colors.HexColor("#EF4444")
C_ORANGE = colors.HexColor("#F97316")
C_YELLOW = colors.HexColor("#EAB308")

SEVERITY_COLORS = {
    "critical": C_RED,
    "high": C_ORANGE,
    "medium": C_YELLOW,
    "low": colors.HexColor("#3B82F6"),
    "secure": C_GREEN,
}

FONT = "Helvetica"


def _make_styles():
    """Create document paragraph styles."""
    styles = getSampleStyleSheet()

    s = {
        "title": ParagraphStyle("RPTitle", parent=styles["Normal"], fontName=f"{FONT}-Bold",
                                fontSize=22, leading=28, textColor=C_BLUE, spaceAfter=6),
        "h1": ParagraphStyle("RPH1", parent=styles["Normal"], fontName=f"{FONT}-Bold",
                             fontSize=14, leading=18, textColor=C_BLUE, spaceBefore=12, spaceAfter=6),
        "h2": ParagraphStyle("RPH2", parent=styles["Normal"], fontName=f"{FONT}-Bold",
                             fontSize=11, leading=15, textColor=C_TEXT, spaceBefore=8, spaceAfter=4),
        "body": ParagraphStyle("RPBody", parent=styles["Normal"], fontName=FONT,
                               fontSize=9, leading=13, textColor=C_TEXT, spaceAfter=4),
        "small": ParagraphStyle("RPSmall", parent=styles["Normal"], fontName=FONT,
                                fontSize=8, leading=11, textColor=C_MUTED, spaceAfter=2),
        "bullet": ParagraphStyle("RPBullet", parent=styles["Normal"], fontName=FONT,
                                 fontSize=9, leading=13, textColor=C_TEXT,
                                 leftIndent=12, firstLineIndent=-8, spaceAfter=3),
    }
    return s


class _NumberedCanvas(canvas.Canvas):
    """Canvas subclass that adds page numbers and headers."""
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved = []

    def showPage(self):
        self._saved.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._saved)
        for state in self._saved:
            self.__dict__.update(state)
            self._draw_decorations(total)
            canvas.Canvas.showPage(self)
        canvas.Canvas.save(self)

    def _draw_decorations(self, total):
        self.saveState()
        self.setFont(FONT, 7)
        self.setFillColor(C_MUTED)
        if self._pageNumber > 1:
            self.drawString(30, A4[1] - 22, "SecureMailScope — Cryptographic Security Posture Assessment Report")
        self.drawRightString(A4[0] - 30, 20, f"Page {self._pageNumber} of {total}")
        self.drawString(30, 20, "Generated by SecureMailScope | NTRO SIH26159")
        self.restoreState()


def generate_pdf_report(analysis: dict[str, Any]) -> bytes:
    """
    Generate a multi-page PDF forensic report.
    
    Args:
        analysis: Complete analysis result dict.
    
    Returns:
        PDF file as bytes.
    """
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, leftMargin=30, rightMargin=30,
                            topMargin=35, bottomMargin=35)
    s = _make_styles()
    w = A4[0] - 60  # usable width
    story = []

    # ─── COVER PAGE ─────────────────────────────────────────────
    story.append(Spacer(1, 60))
    story.append(Paragraph("SecureMailScope", s["title"]))
    story.append(Paragraph("Cryptographic Security Posture Assessment Report", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=2, color=C_BLUE, spaceAfter=12))

    grade = analysis.get("enterprise_grade", "F")
    score = analysis.get("enterprise_score", 0)
    grade_color = C_GREEN if score >= 80 else (C_YELLOW if score >= 50 else C_RED)

    meta_data = [
        ["Source File:", analysis.get("filename", "N/A")],
        ["Analysis ID:", analysis.get("analysis_id", "N/A")[:8]],
        ["Date:", analysis.get("analyzed_at", "N/A")[:19]],
        ["Processing Time:", f"{analysis.get('processing_time_ms', 0)} ms"],
        ["Enterprise Score:", f"{score} / 100"],
        ["Enterprise Grade:", grade],
        ["Total Sessions:", str(analysis.get("total_sessions", 0))],
        ["Protocols Detected:", ", ".join(analysis.get("protocols_detected", []))],
    ]
    meta_table = Table(meta_data, colWidths=[120, w - 120])
    meta_table.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (0, -1), f"{FONT}-Bold"),
        ("FONTNAME", (1, 0), (1, -1), FONT),
        ("FONTSIZE", (0, 0), (-1, -1), 10),
        ("TEXTCOLOR", (0, 0), (0, -1), C_BLUE),
        ("TEXTCOLOR", (1, 0), (1, -1), C_TEXT),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]))
    story.append(meta_table)
    story.append(PageBreak())

    # ─── EXECUTIVE SUMMARY ──────────────────────────────────────
    story.append(Paragraph("1. Executive Summary", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceAfter=8))

    crit_count = len([v for v in analysis.get("vulnerabilities", []) if str(v.get("severity", "")).lower() == "critical"])
    high_count = len([v for v in analysis.get("vulnerabilities", []) if str(v.get("severity", "")).lower() == "high"])
    fail_count = len([c for c in analysis.get("compliance", []) if c.get("status") == "fail"])

    safe_filename = html.escape(str(analysis.get("filename", "N/A")))
    story.append(Paragraph(
        f"Analysis of <b>{safe_filename}</b> identified "
        f"<b>{analysis.get('total_sessions', 0)}</b> email communication sessions across "
        f"<b>{len(analysis.get('protocols_detected', []))}</b> protocol types. "
        f"The overall cryptographic posture is rated <b>{grade}</b> ({score}/100).",
        s["body"]))

    if crit_count > 0:
        story.append(Paragraph(
            f"<font color='red'><b>⚠ {crit_count} CRITICAL vulnerability(ies) detected requiring immediate remediation.</b></font>",
            s["body"]))

    story.append(Spacer(1, 8))

    # ─── SESSION DETAILS TABLE ──────────────────────────────────
    story.append(Paragraph("2. Session Analysis Details", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceAfter=8))

    headers = ["#", "Server", "Protocol", "TLS", "Cipher", "PFS", "Score"]
    rows = [headers]
    for sess in analysis.get("sessions", []):
        rows.append([
            str(sess["session_id"]),
            sess.get("server_name", "")[:25],
            sess.get("protocol", ""),
            sess.get("tls_version", "None")[:7] if sess.get("tls_version") else "Clear",
            (sess.get("cipher_suite_name") or "None")[:20],
            "Yes" if sess.get("has_forward_secrecy") else "No",
            str(sess.get("session_score", 0)),
        ])

    col_widths = [25, 130, 55, 50, 140, 30, 40]
    t = Table(rows, colWidths=col_widths)
    t.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), f"{FONT}-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), C_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, C_BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, C_BG]),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(t)
    story.append(Spacer(1, 12))

    # ─── VULNERABILITY FINDINGS ─────────────────────────────────
    story.append(Paragraph("3. Vulnerability Findings", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceAfter=8))

    vulns = analysis.get("vulnerabilities", [])
    if not vulns:
        story.append(Paragraph("No vulnerabilities detected. All sessions meet security requirements.", s["body"]))
    else:
        for v in vulns:
            raw_sev = str(v.get("severity", "medium")).lower()
            sev = raw_sev.upper()
            sev_color = SEVERITY_COLORS.get(raw_sev, C_MUTED)
            v_title = html.escape(str(v.get("title", "")))
            v_desc = html.escape(str(v.get("description", "")))
            v_remed = html.escape(str(v.get("remediation", "")))
            story.append(KeepTogether([
                Paragraph(f"<font color='{sev_color.hexval()}'>[{sev}]</font> <b>{v_title}</b>", s["body"]),
                Paragraph(v_desc, s["small"]),
                Paragraph(f"<b>Remediation:</b> {v_remed}", s["small"]),
                Spacer(1, 6),
            ]))

    story.append(Spacer(1, 8))

    # ─── COMPLIANCE CHECKLIST ───────────────────────────────────
    story.append(Paragraph("4. Compliance Assessment", s["h1"]))
    story.append(HRFlowable(width="100%", thickness=0.5, color=C_BORDER, spaceAfter=8))

    comp_headers = ["Status", "Standard", "Section", "Requirement"]
    comp_rows = [comp_headers]
    for c in analysis.get("compliance", []):
        icon = "✓ PASS" if c["status"] == "pass" else ("✗ FAIL" if c["status"] == "fail" else "⚠ WARN")
        comp_rows.append([icon, c["standard"], c["section"], c["requirement"][:60]])

    ct = Table(comp_rows, colWidths=[55, 110, 60, w - 225])
    ct.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, 0), f"{FONT}-Bold"),
        ("FONTSIZE", (0, 0), (-1, -1), 8),
        ("BACKGROUND", (0, 0), (-1, 0), C_BLUE),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, C_BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("ROWBACKGROUNDS", (0, 1), (-1, -1), [colors.white, C_BG]),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
        ("TOPPADDING", (0, 0), (-1, -1), 3),
    ]))
    story.append(ct)

    # Build PDF
    doc.build(story, canvasmaker=_NumberedCanvas)
    return buf.getvalue()
