import { AnalysisResult } from "./types";

export const MOCK_RESULT: AnalysisResult = {
  analysis_id: "mock-001",
  filename: "enterprise_mail_capture.pcap",
  file_size_bytes: 2458624,
  analyzed_at: "2026-09-30T15:00:00Z",
  processing_time_ms: 1250,
  enterprise_score: 42,
  enterprise_grade: "F",
  total_sessions: 4,
  total_packets: 847,
  protocols_detected: ["SMTP", "SMTPS", "IMAPS"],
  sessions: [
    {
      session_id: 1,
      src_ip: "192.168.1.100",
      src_port: 49152,
      dst_ip: "10.0.0.5",
      dst_port: 465,
      server_name: "mail.secure-gov.in",
      protocol: "SMTPS",
      timestamp: "2026-09-30T14:55:01Z",
      is_encrypted: true,
      starttls_detected: false,
      starttls_stripped: false,
      tls_version: "TLS 1.3",
      cipher_suite_hex: "0x1301",
      cipher_suite_name: "TLS_AES_256_GCM_SHA384",
      cipher_severity: "secure",
      key_exchange: "ECDHE",
      has_forward_secrecy: true,
      ja3_hash: "a0e9f5d64349fb13191bc781f81f42e1",
      ja3_client_name: "Mozilla Thunderbird",
      ja3_is_known: true,
      certificate: {
        subject_cn: "mail.secure-gov.in",
        issuer_cn: "Let's Encrypt Authority X3",
        serial_number: "03:A1:B2:C3:D4",
        not_before: "2026-06-01T00:00:00Z",
        not_after: "2026-12-01T00:00:00Z",
        is_expired: false,
        is_not_yet_valid: false,
        is_self_signed: false,
        validity_days: 183,
        days_remaining: 62,
        signature_algorithm: "sha256WithRSAEncryption",
        signature_hash: "SHA-256",
        is_weak_signature: false,
        public_key_type: "RSA",
        public_key_bits: 2048,
        is_weak_key: false,
        san_entries: ["mail.secure-gov.in", "smtp.secure-gov.in"],
      },
      session_score: 98,
      session_grade: "A+",
      session_severity: "secure",
      scoring_breakdown: {
        protocol_penalty: 0,
        cipher_penalty: 0,
        pfs_penalty: 0,
        cert_penalty: 0,
        anomaly_penalty: 0,
        raw_score: 100,
        final_score: 98,
      },
    },
    {
      session_id: 2,
      src_ip: "192.168.1.101",
      src_port: 49200,
      dst_ip: "10.0.0.10",
      dst_port: 25,
      server_name: "legacy-mail.corp.in",
      protocol: "SMTP",
      timestamp: "2026-09-30T14:55:12Z",
      is_encrypted: true,
      starttls_detected: true,
      starttls_stripped: false,
      tls_version: "TLS 1.0",
      cipher_suite_hex: "0x000A",
      cipher_suite_name: "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
      cipher_severity: "high",
      key_exchange: "RSA",
      has_forward_secrecy: false,
      ja3_hash: "b38454238e55e098a73b94a08f7db061",
      ja3_client_name: null,
      ja3_is_known: false,
      certificate: {
        subject_cn: "legacy-mail.corp.in",
        issuer_cn: "legacy-mail.corp.in",
        serial_number: "01:00:00:01",
        not_before: "2020-01-01T00:00:00Z",
        not_after: "2025-01-01T00:00:00Z",
        is_expired: true,
        is_not_yet_valid: false,
        is_self_signed: true,
        validity_days: 1826,
        days_remaining: -637,
        signature_algorithm: "sha1WithRSAEncryption",
        signature_hash: "SHA-1",
        is_weak_signature: true,
        public_key_type: "RSA",
        public_key_bits: 1024,
        is_weak_key: true,
        san_entries: [],
      },
      session_score: 0,
      session_grade: "F",
      session_severity: "critical",
      scoring_breakdown: {
        protocol_penalty: -25,
        cipher_penalty: -30,
        pfs_penalty: -20,
        cert_penalty: -30,
        anomaly_penalty: -15,
        raw_score: -20,
        final_score: 0,
      },
    },
    {
      session_id: 3,
      src_ip: "192.168.1.102",
      src_port: 49300,
      dst_ip: "10.0.0.15",
      dst_port: 587,
      server_name: "10.0.0.15",
      protocol: "SMTP",
      timestamp: "2026-09-30T14:55:30Z",
      is_encrypted: false,
      starttls_detected: false,
      starttls_stripped: true,
      tls_version: null,
      cipher_suite_hex: null,
      cipher_suite_name: null,
      cipher_severity: null,
      key_exchange: null,
      has_forward_secrecy: false,
      ja3_hash: null,
      ja3_client_name: null,
      ja3_is_known: false,
      certificate: null,
      session_score: 0,
      session_grade: "F",
      session_severity: "critical",
      scoring_breakdown: {
        protocol_penalty: -40,
        cipher_penalty: -30,
        pfs_penalty: -20,
        cert_penalty: 0,
        anomaly_penalty: -15,
        raw_score: -5,
        final_score: 0,
      },
    },
    {
      session_id: 4,
      src_ip: "192.168.1.103",
      src_port: 49400,
      dst_ip: "10.0.0.20",
      dst_port: 993,
      server_name: "imap.department.gov.in",
      protocol: "IMAPS",
      timestamp: "2026-09-30T14:56:05Z",
      is_encrypted: true,
      starttls_detected: false,
      starttls_stripped: false,
      tls_version: "TLS 1.2",
      cipher_suite_hex: "0xC02F",
      cipher_suite_name: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      cipher_severity: "secure",
      key_exchange: "ECDHE",
      has_forward_secrecy: true,
      ja3_hash: "c12f54a1b2c3d4e5f6789012abcd3456",
      ja3_client_name: "Microsoft Outlook",
      ja3_is_known: true,
      certificate: {
        subject_cn: "imap.department.gov.in",
        issuer_cn: "DigiCert Global Root G2",
        serial_number: "0A:B1:C2:D3:E4",
        not_before: "2026-03-15T00:00:00Z",
        not_after: "2027-03-15T00:00:00Z",
        is_expired: false,
        is_not_yet_valid: false,
        is_self_signed: false,
        validity_days: 365,
        days_remaining: 166,
        signature_algorithm: "sha256WithRSAEncryption",
        signature_hash: "SHA-256",
        is_weak_signature: false,
        public_key_type: "RSA",
        public_key_bits: 4096,
        is_weak_key: false,
        san_entries: ["imap.department.gov.in", "mail.department.gov.in"],
      },
      session_score: 92,
      session_grade: "A+",
      session_severity: "secure",
      scoring_breakdown: {
        protocol_penalty: 0,
        cipher_penalty: 0,
        pfs_penalty: 0,
        cert_penalty: 0,
        anomaly_penalty: 0,
        raw_score: 100,
        final_score: 92,
      },
    },
  ],
  vulnerabilities: [
    {
      id: "VULN-001",
      severity: "critical",
      title: "STRIPTLS Downgrade Attack Detected",
      description:
        "Session #3: cleartext SMTP on port 587 without STARTTLS negotiation. Credentials transmitted in plaintext, consistent with active STRIPTLS MitM attack.",
      affected_sessions: [3],
      cve_references: [],
      nist_reference: "NIST SP 800-52r2 §3.1",
      remediation:
        "Deploy MTA-STS (RFC 8461) and DANE/TLSA DNS records. Reject plaintext fallback on submission ports.",
    },
    {
      id: "VULN-002",
      severity: "critical",
      title: "Expired Self-Signed Certificate (1024-bit RSA)",
      description:
        "Session #2: self-signed certificate expired 637 days ago, SHA-1 signature, 1024-bit RSA key vulnerable to offline factoring.",
      affected_sessions: [2],
      cve_references: [],
      nist_reference: "NIST SP 800-52r2 §3.4",
      remediation:
        "Replace with CA-signed certificate using SHA-256 and minimum 2048-bit RSA key.",
    },
    {
      id: "VULN-003",
      severity: "high",
      title: "Deprecated TLS 1.0 with 3DES Cipher",
      description:
        "Session #2: TLS 1.0 with TLS_RSA_WITH_3DES_EDE_CBC_SHA. Vulnerable to BEAST (CVE-2011-3389) and Sweet32 (CVE-2016-2183) attacks.",
      affected_sessions: [2],
      cve_references: ["CVE-2016-2183", "CVE-2011-3389"],
      nist_reference: "NIST SP 800-52r2 §3.2.1",
      remediation:
        "Upgrade to TLS 1.2+ with AES-GCM cipher suites. Disable TLS 1.0 and 3DES.",
    },
    {
      id: "VULN-004",
      severity: "high",
      title: "No Forward Secrecy (Static RSA Key Exchange)",
      description:
        "Session #2: static RSA key exchange. Historical sessions decryptable if server private key is compromised.",
      affected_sessions: [2],
      cve_references: ["CVE-2017-13099"],
      nist_reference: "NIST SP 800-52r2 §3.3.1",
      remediation:
        "Configure server to prefer ECDHE key exchange. Disable static RSA cipher suites.",
    },
  ],
  compliance: [
    {
      id: "NIST-3.1",
      standard: "NIST SP 800-52r2",
      section: "§3.1",
      requirement: "TLS 1.2 or higher enforced",
      status: "fail",
      details: "TLS 1.0 in session #2",
    },
    {
      id: "NIST-3.2.1",
      standard: "NIST SP 800-52r2",
      section: "§3.2.1",
      requirement: "No deprecated protocols",
      status: "fail",
      details: "TLS 1.0 detected",
    },
    {
      id: "NIST-3.3.1",
      standard: "NIST SP 800-52r2",
      section: "§3.3.1",
      requirement: "Forward secrecy (ECDHE/DHE)",
      status: "fail",
      details: "Static RSA in session #2",
    },
    {
      id: "NIST-3.3.2",
      standard: "NIST SP 800-52r2",
      section: "§3.3.2",
      requirement: "AEAD cipher modes required",
      status: "fail",
      details: "3DES-CBC in session #2",
    },
    {
      id: "NIST-3.4",
      standard: "NIST SP 800-52r2",
      section: "§3.4",
      requirement: "Valid CA-signed certificates",
      status: "fail",
      details: "Self-signed expired cert",
    },
    {
      id: "NIST-3.5",
      standard: "NIST SP 800-52r2",
      section: "§3.5",
      requirement: "RSA keys ≥ 2048 bits",
      status: "fail",
      details: "1024-bit key in session #2",
    },
    {
      id: "RFC-8314",
      standard: "RFC 8314",
      section: "§3",
      requirement: "Implicit TLS preferred",
      status: "pass",
      details: "SMTPS and IMAPS detected",
    },
    {
      id: "RFC-8996",
      standard: "RFC 8996",
      section: "Full",
      requirement: "TLS 1.0/1.1 prohibited",
      status: "fail",
      details: "TLS 1.0 in session #2",
    },
  ],
  protocol_distribution: [
    { name: "TLS 1.3", value: 1, color: "#22C55E" },
    { name: "TLS 1.2", value: 1, color: "#3B82F6" },
    { name: "TLS 1.0", value: 1, color: "#F97316" },
    { name: "Cleartext", value: 1, color: "#EF4444" },
  ],
  cipher_distribution: [
    { name: "AES-256-GCM", count: 1, severity: "secure", color: "#22C55E" },
    { name: "AES-128-GCM", count: 1, severity: "secure", color: "#22C55E" },
    { name: "3DES-CBC", count: 1, severity: "high", color: "#F97316" },
    { name: "None (Cleartext)", count: 1, severity: "critical", color: "#EF4444" },
  ],
  certificate_summary: [
    {
      server_name: "mail.secure-gov.in",
      subject_cn: "mail.secure-gov.in",
      is_expired: false,
      is_self_signed: false,
      is_weak_signature: false,
      is_weak_key: false,
      days_remaining: 62,
      overall_status: "secure",
    },
    {
      server_name: "legacy-mail.corp.in",
      subject_cn: "legacy-mail.corp.in",
      is_expired: true,
      is_self_signed: true,
      is_weak_signature: true,
      is_weak_key: true,
      days_remaining: -637,
      overall_status: "critical",
    },
    {
      server_name: "imap.department.gov.in",
      subject_cn: "imap.department.gov.in",
      is_expired: false,
      is_self_signed: false,
      is_weak_signature: false,
      is_weak_key: false,
      days_remaining: 166,
      overall_status: "secure",
    },
  ],
};
