import { AnalysisResult, EvidenceCase } from "./types";
import { CASE_1_INSPECTION, CASE_2_INSPECTION, CASE_3_INSPECTION, CASE_4_IMAPS_INSPECTION } from "./mock-cases";

// CASE 01: Hardened TLS 1.3
export const CASE_01_DATA: AnalysisResult = {
  analysis_id: "CASE-01",
  filename: "ntro_hardened_tls13.pcap",
  file_size_bytes: 524288,
  analyzed_at: "2026-09-30T16:00:00Z",
  processing_time_ms: 320,
  enterprise_score: 98,
  enterprise_grade: "A+",
  total_sessions: 2,
  total_packets: 412,
  protocols_detected: ["SMTPS", "IMAPS"],
  sessions: [
    {
      session_id: 1,
      src_ip: "10.14.20.101",
      src_port: 52410,
      dst_ip: "10.0.1.25",
      dst_port: 465,
      server_name: "smtp-in.defense.gov.in",
      protocol: "SMTPS",
      timestamp: "2026-09-30T15:58:12Z",
      is_encrypted: true,
      starttls_detected: false,
      starttls_stripped: false,
      tls_version: "TLS 1.3",
      cipher_suite_hex: "0x1301",
      cipher_suite_name: "TLS_AES_256_GCM_SHA384",
      cipher_severity: "secure",
      key_exchange: "ECDHE (X25519)",
      has_forward_secrecy: true,
      ja3_hash: "a0e9f5d64349fb13191bc781f81f42e1",
      ja3_client_name: "Mozilla Thunderbird / Linux Defense Node",
      ja3_is_known: true,
      certificate: {
        subject_cn: "smtp-in.defense.gov.in",
        issuer_cn: "National Public Key Infrastructure CA G3",
        serial_number: "20:26:09:A1:B2:C3",
        not_before: "2026-01-01T00:00:00Z",
        not_after: "2027-01-01T00:00:00Z",
        is_expired: false,
        is_not_yet_valid: false,
        is_self_signed: false,
        validity_days: 365,
        days_remaining: 93,
        signature_algorithm: "ecdsa-with-SHA384",
        signature_hash: "SHA-384",
        is_weak_signature: false,
        public_key_type: "ECDSA (secp384r1)",
        public_key_bits: 384,
        is_weak_key: false,
        san_entries: ["smtp-in.defense.gov.in", "mail.defense.gov.in"],
      },
      session_score: 100,
      session_grade: "A+",
      session_severity: "secure",
      scoring_breakdown: {
        protocol_penalty: 0,
        cipher_penalty: 0,
        pfs_penalty: 0,
        cert_penalty: 0,
        anomaly_penalty: 0,
        raw_score: 100,
        final_score: 100,
      },
      forensic_inspection: CASE_1_INSPECTION,
    },
    {
      session_id: 2,
      src_ip: "10.14.20.102",
      src_port: 52412,
      dst_ip: "10.0.1.30",
      dst_port: 993,
      server_name: "imap.mil.in",
      protocol: "IMAPS",
      timestamp: "2026-09-30T15:58:30Z",
      is_encrypted: true,
      starttls_detected: false,
      starttls_stripped: false,
      tls_version: "TLS 1.3",
      cipher_suite_hex: "0x1302",
      cipher_suite_name: "TLS_CHACHA20_POLY1305_SHA256",
      cipher_severity: "secure",
      key_exchange: "ECDHE (X25519)",
      has_forward_secrecy: true,
      ja3_hash: "c12f54a1b2c3d4e5f6789012abcd3456",
      ja3_client_name: "Defense SecureMail Agent",
      ja3_is_known: true,
      certificate: {
        subject_cn: "imap.mil.in",
        issuer_cn: "National Public Key Infrastructure CA G3",
        serial_number: "20:26:09:D4:E5:F6",
        not_before: "2026-02-01T00:00:00Z",
        not_after: "2027-02-01T00:00:00Z",
        is_expired: false,
        is_not_yet_valid: false,
        is_self_signed: false,
        validity_days: 365,
        days_remaining: 124,
        signature_algorithm: "ecdsa-with-SHA384",
        signature_hash: "SHA-384",
        is_weak_signature: false,
        public_key_type: "ECDSA (secp384r1)",
        public_key_bits: 384,
        is_weak_key: false,
        san_entries: ["imap.mil.in", "mailgw.mil.in"],
      },
      session_score: 96,
      session_grade: "A+",
      session_severity: "secure",
      scoring_breakdown: {
        protocol_penalty: 0,
        cipher_penalty: 0,
        pfs_penalty: 0,
        cert_penalty: 0,
        anomaly_penalty: 0,
        raw_score: 100,
        final_score: 96,
      },
      forensic_inspection: CASE_1_INSPECTION,
    },
  ],
  vulnerabilities: [],
  compliance: [
    { id: "NIST-3.1", standard: "NIST SP 800-52r2", section: "§3.1", requirement: "TLS 1.2 or higher enforced", status: "pass", details: "All flows enforce TLS 1.3" },
    { id: "NIST-3.3.1", standard: "NIST SP 800-52r2", section: "§3.3.1", requirement: "Forward secrecy (ECDHE/DHE)", status: "pass", details: "ECDHE X25519 enforced" },
    { id: "NIST-3.3.2", standard: "NIST SP 800-52r2", section: "§3.3.2", requirement: "AEAD cipher modes required", status: "pass", details: "AES-256-GCM / Poly1305" },
    { id: "RFC-8314", standard: "RFC 8314", section: "§3", requirement: "Implicit TLS preferred", status: "pass", details: "Direct SMTPS (465) & IMAPS (993)" },
  ],
  protocol_distribution: [{ name: "TLS 1.3", value: 2, color: "#22C55E" }],
  cipher_distribution: [
    { name: "AES-256-GCM", count: 1, severity: "secure", color: "#22C55E" },
    { name: "CHACHA20-POLY1305", count: 1, severity: "secure", color: "#22C55E" },
  ],
  certificate_summary: [
    { server_name: "smtp-in.defense.gov.in", subject_cn: "smtp-in.defense.gov.in", is_expired: false, is_self_signed: false, is_weak_signature: false, is_weak_key: false, days_remaining: 93, overall_status: "secure" },
  ],
};

// CASE 02: STRIPTLS MitM Downgrade
export const CASE_02_DATA: AnalysisResult = {
  analysis_id: "CASE-02",
  filename: "striptls_mitm_tamper.pcap",
  file_size_bytes: 284160,
  analyzed_at: "2026-09-30T16:05:00Z",
  processing_time_ms: 245,
  enterprise_score: 14,
  enterprise_grade: "F",
  total_sessions: 1,
  total_packets: 188,
  protocols_detected: ["SMTP"],
  sessions: [
    {
      session_id: 1,
      src_ip: "192.168.10.45",
      src_port: 54120,
      dst_ip: "198.51.100.25",
      dst_port: 587,
      server_name: "mailgw-01.external.org",
      protocol: "SMTP",
      timestamp: "2026-09-30T16:02:14Z",
      is_encrypted: false,
      starttls_detected: false,
      starttls_stripped: true,
      tls_version: null,
      cipher_suite_hex: null,
      cipher_suite_name: null,
      cipher_severity: null,
      key_exchange: null,
      has_forward_secrecy: false,
      ja3_hash: null,
      ja3_client_name: null,
      ja3_is_known: false,
      certificate: null,
      session_score: 14,
      session_grade: "F",
      session_severity: "critical",
      scoring_breakdown: {
        protocol_penalty: -45,
        cipher_penalty: -30,
        pfs_penalty: -20,
        cert_penalty: 0,
        anomaly_penalty: -25,
        raw_score: -20,
        final_score: 14,
      },
      forensic_inspection: CASE_2_INSPECTION,
    },
  ],
  vulnerabilities: [
    {
      id: "VULN-001",
      severity: "critical",
      title: "STRIPTLS Active Downgrade MitM Attack",
      description: "Session #1: Inline network tampering detected on port 587. Adversary stripped '250-STARTTLS' from ESMTP capabilities. Client proceeded with plaintext AUTH LOGIN, leaking credentials.",
      affected_sessions: [1],
      cve_references: ["CVE-2014-3566", "CVE-2015-4000"],
      nist_reference: "NIST SP 800-52r2 §3.1",
      mitre_attack_id: "T1557.002",
      mitre_attack_technique: "Adversary-in-the-Middle: Protocol Downgrade",
      mitre_d3fend_id: "D3-EAC",
      remediation: "Deploy MTA-STS (RFC 8461) and enforce TLS-required policy on submission port 587.",
    },
    {
      id: "VULN-002",
      severity: "critical",
      title: "Plaintext Credential Wire Leakage",
      description: "Administrative credentials transmitted without transport encryption (Base64 admin@gov.in visible in raw wire payload).",
      affected_sessions: [1],
      cve_references: [],
      nist_reference: "NIST SP 800-52r2 §3.1",
      mitre_attack_id: "T1552.001",
      mitre_attack_technique: "Unsecured Credentials: Credentials in Transport",
      mitre_d3fend_id: "D3-PA",
      remediation: "Terminate cleartext authentication handlers and enforce strict SMTPS (Port 465).",
    },
  ],
  compliance: [
    { id: "NIST-3.1", standard: "NIST SP 800-52r2", section: "§3.1", requirement: "TLS 1.2 or higher enforced", status: "fail", details: "Cleartext transmission on submission port 587" },
    { id: "RFC-8314", standard: "RFC 8314", section: "§3", requirement: "Implicit TLS preferred", status: "fail", details: "Opportunistic STARTTLS tampered, cleartext fallback" },
  ],
  protocol_distribution: [{ name: "Cleartext", value: 1, color: "#EF4444" }],
  cipher_distribution: [{ name: "None (Cleartext)", count: 1, severity: "critical", color: "#EF4444" }],
  certificate_summary: [],
};

// CASE 03: Legacy 3DES / RSA
export const CASE_03_DATA: AnalysisResult = {
  analysis_id: "CASE-03",
  filename: "legacy_3des_rsa_obsolete.pcap",
  file_size_bytes: 412000,
  analyzed_at: "2026-09-30T16:10:00Z",
  processing_time_ms: 290,
  enterprise_score: 24,
  enterprise_grade: "F",
  total_sessions: 1,
  total_packets: 230,
  protocols_detected: ["SMTP"],
  sessions: [
    {
      session_id: 1,
      src_ip: "10.200.4.15",
      src_port: 48920,
      dst_ip: "10.200.1.10",
      dst_port: 25,
      server_name: "legacy-gateway.central.in",
      protocol: "SMTP",
      timestamp: "2026-09-30T16:08:44Z",
      is_encrypted: true,
      starttls_detected: true,
      starttls_stripped: false,
      tls_version: "TLS 1.0",
      cipher_suite_hex: "0x000A",
      cipher_suite_name: "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
      cipher_severity: "high",
      key_exchange: "Static RSA",
      has_forward_secrecy: false,
      ja3_hash: "b38454238e55e098a73b94a08f7db061",
      ja3_client_name: "Legacy MUA / Outlook 2007",
      ja3_is_known: false,
      certificate: {
        subject_cn: "legacy-gateway.central.in",
        issuer_cn: "legacy-gateway.central.in",
        serial_number: "01:00:00:01",
        not_before: "2020-01-01T00:00:00Z",
        not_after: "2025-01-01T00:00:00Z",
        is_expired: true,
        is_not_yet_valid: false,
        is_self_signed: true,
        validity_days: 1826,
        days_remaining: -637,
        signature_algorithm: "sha1WithRSAEncryption",
        signature_hash: "SHA-1",
        is_weak_signature: true,
        public_key_type: "RSA",
        public_key_bits: 1024,
        is_weak_key: true,
        san_entries: [],
      },
      session_score: 24,
      session_grade: "F",
      session_severity: "critical",
      scoring_breakdown: {
        protocol_penalty: -25,
        cipher_penalty: -30,
        pfs_penalty: -20,
        cert_penalty: -30,
        anomaly_penalty: -15,
        raw_score: -20,
        final_score: 24,
      },
      forensic_inspection: CASE_3_INSPECTION,
    },
  ],
  vulnerabilities: [
    {
      id: "VULN-003",
      severity: "high",
      title: "Deprecated TLS 1.0 with 3DES Cipher (Sweet32 / BEAST)",
      description: "Session #1: TLS 1.0 with TLS_RSA_WITH_3DES_EDE_CBC_SHA. Subject to 64-bit block collision attacks (CVE-2016-2183) and BEAST (CVE-2011-3389).",
      affected_sessions: [1],
      cve_references: ["CVE-2016-2183", "CVE-2011-3389"],
      nist_reference: "NIST SP 800-52r2 §3.2.1",
      mitre_attack_id: "T1600.001",
      mitre_attack_technique: "Weaken Encryption: Deprecated Protocol Fallback",
      mitre_d3fend_id: "D3-CSM",
      remediation: "Deprecate TLS 1.0/1.1; enable TLS 1.2+ with AES-GCM suites.",
    },
    {
      id: "VULN-004",
      severity: "critical",
      title: "Expired 1024-Bit Self-Signed Certificate with SHA-1",
      description: "Certificate expired 637 days ago. Factorable 1024-bit RSA key and deprecated SHA-1 collision vulnerability.",
      affected_sessions: [1],
      cve_references: ["CVE-2017-13099"],
      nist_reference: "NIST SP 800-52r2 §3.4",
      mitre_attack_id: "T1588.004",
      mitre_attack_technique: "Obtain Capabilities: Digital Certificates",
      mitre_d3fend_id: "D3-CV",
      remediation: "Re-issue certificate under valid CA with minimum RSA 2048-bit or ECDSA P-256.",
    },
  ],
  compliance: [
    { id: "NIST-3.1", standard: "NIST SP 800-52r2", section: "§3.1", requirement: "TLS 1.2 or higher enforced", status: "fail", details: "TLS 1.0 prohibited" },
    { id: "NIST-3.3.1", standard: "NIST SP 800-52r2", section: "§3.3.1", requirement: "Forward secrecy (ECDHE/DHE)", status: "fail", details: "Static RSA key exchange" },
    { id: "RFC-8996", standard: "RFC 8996", section: "Full", requirement: "TLS 1.0/1.1 prohibited", status: "fail", details: "TLS 1.0 detected" },
  ],
  protocol_distribution: [{ name: "TLS 1.0", value: 1, color: "#F97316" }],
  cipher_distribution: [{ name: "3DES-CBC", count: 1, severity: "high", color: "#F97316" }],
  certificate_summary: [
    { server_name: "legacy-gateway.central.in", subject_cn: "legacy-gateway.central.in", is_expired: true, is_self_signed: true, is_weak_signature: true, is_weak_key: true, days_remaining: -637, overall_status: "critical" },
  ],
};

// CASE 04: Enterprise Mixed (Combines all 4 forensic flows)
export const CASE_04_DATA: AnalysisResult = {
  analysis_id: "CASE-04",
  filename: "enterprise_mail_capture.pcap",
  file_size_bytes: 2458624,
  analyzed_at: "2026-09-30T15:00:00Z",
  processing_time_ms: 1250,
  enterprise_score: 42,
  enterprise_grade: "F",
  total_sessions: 4,
  total_packets: 847,
  protocols_detected: ["SMTP", "SMTPS", "IMAPS"],
  sessions: [
    {
      session_id: 1,
      src_ip: "192.168.1.100",
      src_port: 49152,
      dst_ip: "10.0.0.5",
      dst_port: 465,
      server_name: "mail.secure-gov.in",
      protocol: "SMTPS",
      timestamp: "2026-09-30T14:55:01Z",
      is_encrypted: true,
      starttls_detected: false,
      starttls_stripped: false,
      tls_version: "TLS 1.3",
      cipher_suite_hex: "0x1301",
      cipher_suite_name: "TLS_AES_256_GCM_SHA384",
      cipher_severity: "secure",
      key_exchange: "ECDHE",
      has_forward_secrecy: true,
      ja3_hash: "a0e9f5d64349fb13191bc781f81f42e1",
      ja3_client_name: "Mozilla Thunderbird",
      ja3_is_known: true,
      certificate: {
        subject_cn: "mail.secure-gov.in",
        issuer_cn: "Let's Encrypt Authority X3",
        serial_number: "03:A1:B2:C3:D4",
        not_before: "2026-06-01T00:00:00Z",
        not_after: "2026-12-01T00:00:00Z",
        is_expired: false,
        is_not_yet_valid: false,
        is_self_signed: false,
        validity_days: 183,
        days_remaining: 62,
        signature_algorithm: "sha256WithRSAEncryption",
        signature_hash: "SHA-256",
        is_weak_signature: false,
        public_key_type: "RSA",
        public_key_bits: 2048,
        is_weak_key: false,
        san_entries: ["mail.secure-gov.in", "smtp.secure-gov.in"],
      },
      session_score: 98,
      session_grade: "A+",
      session_severity: "secure",
      scoring_breakdown: {
        protocol_penalty: 0,
        cipher_penalty: 0,
        pfs_penalty: 0,
        cert_penalty: 0,
        anomaly_penalty: 0,
        raw_score: 100,
        final_score: 98,
      },
      forensic_inspection: CASE_1_INSPECTION,
    },
    {
      session_id: 2,
      src_ip: "192.168.1.101",
      src_port: 49200,
      dst_ip: "10.0.0.10",
      dst_port: 25,
      server_name: "legacy-mail.corp.in",
      protocol: "SMTP",
      timestamp: "2026-09-30T14:55:12Z",
      is_encrypted: true,
      starttls_detected: true,
      starttls_stripped: false,
      tls_version: "TLS 1.0",
      cipher_suite_hex: "0x000A",
      cipher_suite_name: "TLS_RSA_WITH_3DES_EDE_CBC_SHA",
      cipher_severity: "high",
      key_exchange: "RSA",
      has_forward_secrecy: false,
      ja3_hash: "b38454238e55e098a73b94a08f7db061",
      ja3_client_name: null,
      ja3_is_known: false,
      certificate: {
        subject_cn: "legacy-mail.corp.in",
        issuer_cn: "legacy-mail.corp.in",
        serial_number: "01:00:00:01",
        not_before: "2020-01-01T00:00:00Z",
        not_after: "2025-01-01T00:00:00Z",
        is_expired: true,
        is_not_yet_valid: false,
        is_self_signed: true,
        validity_days: 1826,
        days_remaining: -637,
        signature_algorithm: "sha1WithRSAEncryption",
        signature_hash: "SHA-1",
        is_weak_signature: true,
        public_key_type: "RSA",
        public_key_bits: 1024,
        is_weak_key: true,
        san_entries: [],
      },
      session_score: 0,
      session_grade: "F",
      session_severity: "critical",
      scoring_breakdown: {
        protocol_penalty: -25,
        cipher_penalty: -30,
        pfs_penalty: -20,
        cert_penalty: -30,
        anomaly_penalty: -15,
        raw_score: -20,
        final_score: 0,
      },
      forensic_inspection: CASE_3_INSPECTION,
    },
    {
      session_id: 3,
      src_ip: "192.168.1.102",
      src_port: 49300,
      dst_ip: "10.0.0.15",
      dst_port: 587,
      server_name: "10.0.0.15",
      protocol: "SMTP",
      timestamp: "2026-09-30T14:55:30Z",
      is_encrypted: false,
      starttls_detected: false,
      starttls_stripped: true,
      tls_version: null,
      cipher_suite_hex: null,
      cipher_suite_name: null,
      cipher_severity: null,
      key_exchange: null,
      has_forward_secrecy: false,
      ja3_hash: null,
      ja3_client_name: null,
      ja3_is_known: false,
      certificate: null,
      session_score: 0,
      session_grade: "F",
      session_severity: "critical",
      scoring_breakdown: {
        protocol_penalty: -40,
        cipher_penalty: -30,
        pfs_penalty: -20,
        cert_penalty: 0,
        anomaly_penalty: -15,
        raw_score: -5,
        final_score: 0,
      },
      forensic_inspection: CASE_2_INSPECTION,
    },
    {
      session_id: 4,
      src_ip: "192.168.1.103",
      src_port: 49400,
      dst_ip: "10.0.0.20",
      dst_port: 993,
      server_name: "imap.department.gov.in",
      protocol: "IMAPS",
      timestamp: "2026-09-30T14:56:05Z",
      is_encrypted: true,
      starttls_detected: false,
      starttls_stripped: false,
      tls_version: "TLS 1.2",
      cipher_suite_hex: "0xC02F",
      cipher_suite_name: "TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256",
      cipher_severity: "secure",
      key_exchange: "ECDHE",
      has_forward_secrecy: true,
      ja3_hash: "c12f54a1b2c3d4e5f6789012abcd3456",
      ja3_client_name: "Microsoft Outlook",
      ja3_is_known: true,
      certificate: {
        subject_cn: "imap.department.gov.in",
        issuer_cn: "DigiCert Global Root G2",
        serial_number: "0A:B1:C2:D3:E4",
        not_before: "2026-03-15T00:00:00Z",
        not_after: "2027-03-15T00:00:00Z",
        is_expired: false,
        is_not_yet_valid: false,
        is_self_signed: false,
        validity_days: 365,
        days_remaining: 166,
        signature_algorithm: "sha256WithRSAEncryption",
        signature_hash: "SHA-256",
        is_weak_signature: false,
        public_key_type: "RSA",
        public_key_bits: 4096,
        is_weak_key: false,
        san_entries: ["imap.department.gov.in", "mail.department.gov.in"],
      },
      session_score: 92,
      session_grade: "A+",
      session_severity: "secure",
      scoring_breakdown: {
        protocol_penalty: 0,
        cipher_penalty: 0,
        pfs_penalty: 0,
        cert_penalty: 0,
        anomaly_penalty: 0,
        raw_score: 100,
        final_score: 92,
      },
      forensic_inspection: CASE_4_IMAPS_INSPECTION,
    },
  ],
  vulnerabilities: [
    {
      id: "VULN-001",
      severity: "critical",
      title: "STRIPTLS Downgrade Attack Detected",
      description: "Session #3: cleartext SMTP on port 587 without STARTTLS negotiation. Plaintext credentials transmitted, consistent with active inline STRIPTLS MitM attack.",
      affected_sessions: [3],
      cve_references: [],
      nist_reference: "NIST SP 800-52r2 §3.1",
      mitre_attack_id: "T1557.002",
      mitre_attack_technique: "Adversary-in-the-Middle: Protocol Downgrade",
      mitre_d3fend_id: "D3-EAC",
      remediation: "Deploy MTA-STS (RFC 8461) and DANE/TLSA DNS records. Reject plaintext fallback on submission ports.",
    },
    {
      id: "VULN-002",
      severity: "critical",
      title: "Expired Self-Signed Certificate (1024-bit RSA)",
      description: "Session #2: self-signed certificate expired 637 days ago, SHA-1 signature, 1024-bit RSA key vulnerable to offline factoring.",
      affected_sessions: [2],
      cve_references: [],
      nist_reference: "NIST SP 800-52r2 §3.4",
      mitre_attack_id: "T1588.004",
      mitre_attack_technique: "Obtain Capabilities: Digital Certificates",
      mitre_d3fend_id: "D3-CV",
      remediation: "Replace with CA-signed certificate using SHA-256 and minimum 2048-bit RSA key.",
    },
    {
      id: "VULN-003",
      severity: "high",
      title: "Deprecated TLS 1.0 with 3DES Cipher",
      description: "Session #2: TLS 1.0 with TLS_RSA_WITH_3DES_EDE_CBC_SHA. Vulnerable to BEAST (CVE-2011-3389) and Sweet32 (CVE-2016-2183).",
      affected_sessions: [2],
      cve_references: ["CVE-2016-2183", "CVE-2011-3389"],
      nist_reference: "NIST SP 800-52r2 §3.2.1",
      mitre_attack_id: "T1600.001",
      mitre_attack_technique: "Weaken Encryption: Deprecated Protocol Fallback",
      mitre_d3fend_id: "D3-CSM",
      remediation: "Upgrade to TLS 1.2+ with AES-GCM cipher suites. Disable TLS 1.0 and 3DES.",
    },
    {
      id: "VULN-004",
      severity: "high",
      title: "No Forward Secrecy (Static RSA Key Exchange)",
      description: "Session #2: static RSA key exchange. Historical sessions decryptable if server private key is compromised.",
      affected_sessions: [2],
      cve_references: ["CVE-2017-13099"],
      nist_reference: "NIST SP 800-52r2 §3.3.1",
      mitre_attack_id: "T1600.002",
      mitre_attack_technique: "Weaken Encryption: Weak Cryptographic Algorithms (Static RSA)",
      mitre_d3fend_id: "D3-CSM",
      remediation: "Configure server to prefer ECDHE key exchange. Disable static RSA cipher suites.",
    },
  ],
  compliance: [
    { id: "NIST-3.1", standard: "NIST SP 800-52r2", section: "§3.1", requirement: "TLS 1.2 or higher enforced", status: "fail", details: "TLS 1.0 in session #2" },
    { id: "NIST-3.2.1", standard: "NIST SP 800-52r2", section: "§3.2.1", requirement: "No deprecated protocols", status: "fail", details: "TLS 1.0 detected" },
    { id: "NIST-3.3.1", standard: "NIST SP 800-52r2", section: "§3.3.1", requirement: "Forward secrecy (ECDHE/DHE)", status: "fail", details: "Static RSA in session #2" },
    { id: "NIST-3.3.2", standard: "NIST SP 800-52r2", section: "§3.3.2", requirement: "AEAD cipher modes required", status: "fail", details: "3DES-CBC in session #2" },
    { id: "NIST-3.4", standard: "NIST SP 800-52r2", section: "§3.4", requirement: "Valid CA-signed certificates", status: "fail", details: "Self-signed expired cert" },
    { id: "NIST-3.5", standard: "NIST SP 800-52r2", section: "§3.5", requirement: "RSA keys ≥ 2048 bits", status: "fail", details: "1024-bit key in session #2" },
    { id: "RFC-8314", standard: "RFC 8314", section: "§3", requirement: "Implicit TLS preferred", status: "pass", details: "SMTPS and IMAPS detected" },
    { id: "RFC-8996", standard: "RFC 8996", section: "Full", requirement: "TLS 1.0/1.1 prohibited", status: "fail", details: "TLS 1.0 in session #2" },
  ],
  protocol_distribution: [
    { name: "TLS 1.3", value: 1, color: "#22C55E" },
    { name: "TLS 1.2", value: 1, color: "#3B82F6" },
    { name: "TLS 1.0", value: 1, color: "#F97316" },
    { name: "Cleartext", value: 1, color: "#EF4444" },
  ],
  cipher_distribution: [
    { name: "AES-256-GCM", count: 1, severity: "secure", color: "#22C55E" },
    { name: "AES-128-GCM", count: 1, severity: "secure", color: "#22C55E" },
    { name: "3DES-CBC", count: 1, severity: "high", color: "#F97316" },
    { name: "None (Cleartext)", count: 1, severity: "critical", color: "#EF4444" },
  ],
  certificate_summary: [
    { server_name: "mail.secure-gov.in", subject_cn: "mail.secure-gov.in", is_expired: false, is_self_signed: false, is_weak_signature: false, is_weak_key: false, days_remaining: 62, overall_status: "secure" },
    { server_name: "legacy-mail.corp.in", subject_cn: "legacy-mail.corp.in", is_expired: true, is_self_signed: true, is_weak_signature: true, is_weak_key: true, days_remaining: -637, overall_status: "critical" },
    { server_name: "imap.department.gov.in", subject_cn: "imap.department.gov.in", is_expired: false, is_self_signed: false, is_weak_signature: false, is_weak_key: false, days_remaining: 166, overall_status: "secure" },
  ],
};

export const MOCK_RESULT: AnalysisResult = CASE_04_DATA;

export const EVIDENCE_CASES: EvidenceCase[] = [
  {
    id: "CASE-01",
    case_code: "CASE-01",
    name: "HARDENED_TLS13",
    label: "[CASE-01: HARDENED_TLS13]",
    target_host: "smtp-in.defense.gov.in:465",
    protocol: "SMTPS/IMAPS",
    severity: "secure",
    packet_count: 412,
    stream_count: 2,
    posture_score: 98,
    posture_grade: "A+",
    bpf_filter: "tcp and (port 465 or port 993)",
    description: "Hardened defense-grade TLS 1.3 architecture with X25519, AES-256-GCM, and ECDSA P-384 certificates.",
    data: CASE_01_DATA,
  },
  {
    id: "CASE-02",
    case_code: "CASE-02",
    name: "STRIPTLS_MITM",
    label: "[CASE-02: STRIPTLS_MITM]",
    target_host: "mailgw-01.external.org:587",
    protocol: "SMTP",
    severity: "critical",
    packet_count: 188,
    stream_count: 1,
    posture_score: 14,
    posture_grade: "F",
    bpf_filter: "tcp and port 587",
    description: "Active inline STARTTLS stripping downgrade attack leaking cleartext administrative authentication.",
    data: CASE_02_DATA,
  },
  {
    id: "CASE-03",
    case_code: "CASE-03",
    name: "LEGACY_3DES_RSA",
    label: "[CASE-03: LEGACY_3DES_RSA]",
    target_host: "legacy-gateway.central.in:25",
    protocol: "SMTP",
    severity: "critical",
    packet_count: 230,
    stream_count: 1,
    posture_score: 24,
    posture_grade: "F",
    bpf_filter: "tcp and port 25",
    description: "Obsolete TLS 1.0 negotiation, 3DES cipher collision risk (Sweet32), static RSA, and expired 1024-bit cert.",
    data: CASE_03_DATA,
  },
  {
    id: "CASE-04",
    case_code: "CASE-04",
    name: "ENTERPRISE_MIXED",
    label: "[CASE-04: ENTERPRISE_MIXED]",
    target_host: "mail.secure-gov.in / legacy / external",
    protocol: "MULTI-VECTOR",
    severity: "critical",
    packet_count: 847,
    stream_count: 4,
    posture_score: 42,
    posture_grade: "F",
    bpf_filter: "tcp and (port 25 or 587 or 465 or 993 or 110)",
    description: "Real-world multi-stream enterprise capture displaying full spectrum cryptographic hygiene variance.",
    data: CASE_04_DATA,
  },
];
